### ISSUE TITLE
change circle size

### ISSUE THREAD

**Issue by hshafique** [lmmenge/WatchSpringboard-Prototype#4]
Hello,

I would like to be able to change the circle size to allow for greater magnification. I've tried to change the diameter in the LMSpringboardView class but was not able to get a bigger circle. Can you please advise me on how to accomplish this.

Thanks

**Comment by lmmenge** [comment]
I'm afraid this prototype wasn't coded for that kind of customization. The icon size is hardcoded in various places at 60px (the original iPhone icon size). To change icon size, you must alter every instance of the number "60" to your new value (may I recommend creating a variable for that? extern NSUInteger somewhere?). This will change the size of the icons within each item view.

Then there's the itemDiameter variable in LMSpringboardView which controls the size of the item view area itself.

Then there's tweaking the launch quit mask so that it still fills up the screen on launch/quit. You want to change the "1.2" magic number in [LMViewControllerView launchAppItem:] and [LMViewControllerView quitApp] to do that.

When I built this, I didn't have future proofing and much more customization in mind. Could this be more elegant? Way yes. Necessary for its purpose? Nah, sorry.

I'm going to close this in 24h if you have no follow-ups by then. Best of luck!

**Comment by hshafique** [comment]
Thank you, that was very helpful. Please go ahead and close this issue.
