### ISSUE TITLE
Use of iVars vs properties

### ISSUE THREAD

**Issue by aenewton** [lmmenge/WatchSpringboard-Prototype#7]
Everything appears to be in instance variables as opposed to properties. To follow conventions, these should be changed to properties.

**Comment by aenewton** [comment]
If the author agrees, I would be glad to implement this.

**Comment by lmmenge** [comment]
If you want to improve on this, please feel free to do so. I suggest you create your own fork of this project, though. There might be other people who want to contribute to this. Unfortunately, I'm not dedicating more time to developing this, since this was really meant to be just a prototype.

Your suggestion really is one of the things I would like to have done, if I were to spend more time and make this a "final" library.

**Comment by hamm99922** [comment]
عو المالكي
